spring.application.name=sri_project
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp




spring.datasource.url=jdbc:mysql://localhost:3306/sri_stats_db
spring.datasource.username=Richris
spring.datasource.password=2321
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
